---
weather_data_collection:
  description: Gather real-time weather data for {region} using the ScrapeWebsiteTool
    and update the system to assist in snow-removal planning.
  expected_output: Real-time weather data for {region} updated in the system, providing
    accurate forecasts for snow-removal planning.
  async_execution: false
  agent: weather_monitor
traffic_data_integration:
  description: Scrape traffic data for {region} and feed it into the routing system
    for real-time adjustments to snow-removal routes.
  expected_output: Real-time traffic data for {region} integrated into the routing
    system, allowing for dynamic route adjustments.
  async_execution: false
  agent: route_optimizer
resource_monitoring:
  description: Query inventory levels of salt and fuel using online sources (JSONSearchTool)
    and local inventory files (fuel_inv.json and salt_inv.json when online sources are unavailable)
    to alert when resources are below threshold for {region}.
  expected_output: Updated inventory levels of salt and fuel for {region} from either online
    or local sources, with alerts generated for low resources and clear indication of data source used.
  async_execution: false
  agent: stock_resources_manager
route_optimization:
  description: Continuously optimize snow-removal routes using real-time weather and
    traffic data for {region}, updating fleet assignments as needed.
  expected_output: Optimized snow-removal routes for {region}, with updated fleet
    assignments based on current conditions.
  async_execution: false
  agent: route_optimizer
  context:
  - weather_data_collection
  - traffic_data_integration
stakeholder_communication:
  description: Send notifications and alerts to residents and managers about snow-removal
    schedules and resource statuses for {region}. Generate a detailed HTML report summarizing
    all operations, findings, and recommendations.
  expected_output: |
    1. Timely notifications and alerts sent to stakeholders and residents in {region}
    2. A comprehensive HTML report generated with:
       - Current weather conditions and forecasts
       - Traffic data and route optimizations
       - Resource inventory status
       - Operational recommendations
       - Timestamp and formatting for easy reading
  async_execution: false
  agent: notifications_alerts_manager
  context:
  - resource_monitoring
  - route_optimization
